# Generated by Django 2.0 on 2018-04-05 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('teams', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('user_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_athlete', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(blank=True, max_length=140, null=True)),
                ('league_instance', models.ManyToManyField(blank=True, related_name='league_athletes', to='leagues.League')),
            ],
        ),
        migrations.CreateModel(
            name='AthleteTeamInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_suspended', models.BooleanField(default=False)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='SoccerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField(blank=True, null=True)),
                ('athlete_instance', models.ManyToManyField(related_name='athlete_soccer_stats', to='athletes.Athlete')),
                ('athlete_league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leagues.League')),
                ('athlete_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='athlete',
            name='team_instance',
            field=models.ManyToManyField(blank=True, related_name='team_athletes', through='athletes.AthleteTeamInstance', to='teams.Team'),
        ),
    ]
