# Generated by Django 2.0 on 2018-03-10 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        ('teams', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('user_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(max_length=125)),
                ('league_instance', models.ManyToManyField(blank=True, related_name='league_athletes', to='leagues.League')),
                ('team_instance', models.ManyToManyField(blank=True, related_name='team_athletes', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='SoccerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='athletes.Athlete')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
