# Generated by Django 2.0 on 2018-01-31 01:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leagues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('gameID', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('timeStart', models.TimeField()),
                ('timeEnd', models.TimeField()),
                ('awayTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayTeam', to='teams.Team')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeTeam', to='leagues.LeagueLocations')),
            ],
        ),
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoccerGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('sportID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='soccergame',
            name='gameID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Sport'),
        ),
    ]
