# Generated by Django 2.0 on 2018-04-05 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('abbrev', models.CharField(blank=True, max_length=4, null=True)),
                ('bio', models.CharField(blank=True, max_length=125, null=True)),
                ('primary_color', models.CharField(blank=True, max_length=16, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('division_instance', models.ManyToManyField(blank=True, related_name='division_teams', to='leagues.LeagueDivision')),
            ],
        ),
        migrations.CreateModel(
            name='TeamHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('league_instance', models.ManyToManyField(related_name='league_division', to='leagues.LeagueDivision')),
                ('team_instance', models.ManyToManyField(related_name='team_history', to='teams.Team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMemberTitles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Captain', 'Captain'), ('Co-Captain', 'Co-Captain')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamOwnerPermissionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(blank=True, choices=[('add_athlete', 'Add Athlete'), ('delete_athlete', 'Delete Athlete'), ('suspend_athlete', 'Suspend Athlete'), ('change_name', 'Change Team Name'), ('change_color', 'Change Team Colors')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamOwnerPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_owner_instance', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ManyToManyField(blank=True, related_name='permission_list', to='teams.TeamOwnerPermissionList')),
                ('team_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_owners', to='teams.Team')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.TeamMemberTitles')),
            ],
        ),
    ]
