# Generated by Django 2.0 on 2018-03-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='beta_registration',
            field=models.BooleanField(default=False, verbose_name='Beta Registration'),
        ),
    ]
