# Generated by Django 2.0 on 2018-01-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='credential',
            field=models.CharField(blank=True, choices=[('A', 'Athlete'), ('T', 'Team'), ('L', 'League Organizer'), ('Admin', 'ADMIN')], max_length=200, null=True, verbose_name='Credential'),
        ),
    ]
