# Generated by Django 2.0 on 2018-01-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180122_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
