# Generated by Django 2.0 on 2018-03-23 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180323_1943'),
        ('games', '0001_initial'),
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referee',
            fields=[
                ('user_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_referee', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.CharField(max_length=125)),
                ('game_instance', models.ManyToManyField(blank=True, related_name='game_referee', to='games.Game')),
                ('league_instance', models.ManyToManyField(blank=True, related_name='league_referee', to='leagues.League')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
